### ISSUE TITLE
Unable to run phpmyadmin

### ISSUE THREAD

**Issue by Dutchman1990** [cubiclesoft/portable-apache-maria-db-php-for-windows#4]
Hello, I cant run/access the DB. What URL I should use?

**Comment by cubiclesoft** [comment]
Going to need more info.  phpmyadmin is not included.  This is just a bare, portable install of the three products mentioned in the title.  Local Maria DB management is usually done from the command-line (my personal preference) or a product like Sqlyog Community Edition.

**Comment by Dutchman1990** [comment]
Fixed it. Thanks for the idea BTW
