### ISSUE TITLE
Issue with MariaDB

### ISSUE THREAD

**Issue by blakie21737** [cubiclesoft/portable-apache-maria-db-php-for-windows#5]
Hey I'm loving the idea of this setup as a portable stack but i have an issue with mariadb, when installing i encounter the below issue and maria wont launch when i run start_server.bat 

It doesn't throw any errors when called to start but it just doesn't start.

Sorry if its just me being silly but i cant work it out.

-----
The PHP configuration type to use from the distribution.

PHP config (dev or prod) [dev]:

-----
Configuring.  This should only take a moment to complete.
PHP Warning:  copy(): The first argument to copy() function cannot be a directory in E:\Programs\ConEmu\ConEmu\WAMP\support\install.php on line 144

Warning: copy(): The first argument to copy() function cannot be a directory in E:\Programs\ConEmu\ConEmu\WAMP\support\install.php on line 144
Done.
Press any key to continue . . .

**Comment by blakie21737** [comment]
Just to add some more details for you, i have tried it in the root of my C drive and the root of my USB, i used all default settings then modified settings and have tried doing a reboot and doing a fresh run all of which all attempts encounter this error.

I'm wanting to use this with ConEmu as i can set custom environment variables and have direct command line access to mysql, PHP, NPM, etc at any PC i sit down at and not have to set up variables or worry about having admin access.

**Comment by cubiclesoft** [comment]
Looks like Maria DB doesn't ship with sample INI files anymore.  An INI is required to run, so that decision is not terribly useful for their product.  Basically, it won't work out of the box with a simple file rename.

I've added one of the missing default files.  Try it again.
