### ISSUE TITLE
Apache DocumentRoot outside of SRVROOT

### ISSUE THREAD

**Issue by tiborepcek** [cubiclesoft/portable-apache-maria-db-php-for-windows#9]
Can i use a path outside of defined `SRVROOT` in `httpd.conf`?

Default `DocumentRoot` is `${SRVROOT}/htdocs` but i need to redirect it to the path outside of `apache` directory.

Is it possible?

Thank you.

**Comment by cubiclesoft** [comment]
Yeah, that was supposed to be part of the installation process.  Apparently the string the script looks for in the `http.conf` file changed somewhere along the line.  I've fixed the issue.

`httpd.conf` is supposed to be editable as it is part of Apache, so feel free to modify it.
